name: zameny_flutter
description: Че по заменам?
publish_to: 'none' 
version: 1.0.0+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  web: ^0.5.1
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.3
  get_it: ^7.7.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  flutter_displaymode: ^0.6.0
  talker_flutter: ^4.2.0
  provider: ^6.1.2
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  animated_list_plus: ^0.5.2
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  flutter_native_splash: ^2.4.0
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  dio: ^5.4.3+1
  riverpod: ^2.5.1
  syncfusion_flutter_datepicker: ^25.2.4
  flutter_riverpod: ^2.5.1
  pdf: ^3.10.8
  screenshot: ^3.0.0
  flutter_portal: ^1.1.4
  mobkit_dashed_border: ^0.0.6
  share_plus: ^9.0.0
  uuid: ^4.4.0
  flutter_animate: ^4.5.0
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_lints: ^4.0.0

flutter_native_splash:
  android: true
  web: true
  color: "#121525"
  image: "assets/icon/whale_android.png"
  android_12:
    image: "assets/icon/whale_android.png"
    color: "#121525"
    icon_background_color: "#121525"
# flutter_launcher_icons:
#   image_path: "assets/icon/whale.png"
#   android: true
#   min_sdk_android: 21
#   adaptive_icon_background: "#121525"
#   adaptive_icon_foreground: "assets/icon/whale_android.png"
#   web:
#     generate: true
#     background_color: "#121525"
#     theme_color: "#121525"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    
  fonts:
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Monospace
      fonts: 
        - asset: assets/fonts/SpaceMono-Regular.ttf