name: Flutter PR

on:
 pull_request:
   branches:
     - "main"

jobs:
 build:
   runs-on: ubuntu-latest
   defaults:
    run:
      working-directory: ./Application/Mobile/zameny_flutter
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v2
       with:
         distribution: 'zulu'
         java-version: "12.x"

     - uses: subosito/flutter-action@v1
       with:
         channel: "stable"

     - run: flutter pub get
     - run: flutter build apk --release --split-per-abi

     - name: Push to Releases
       uses: ncipollo/release-action@v1
       with:
        artifacts: "build/app/outputs/flutter-apk/*.apk"
        tag: ${{ github.run_number }}
        token: ${{ secrets.TOKEN }} 